---
- name: "Install docker"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: ubuntu

  tasks:
    - name: Download Install docker script
      get_url:
        url: "https://get.docker.com"
        dest: /home/ubuntu/get-docker.sh

    - name: run script to install docker
      command: "sh /home/ubuntu/get-docker.sh"

    - name: give the privilège to ubuntu
      user:
        name: ubuntu
        append: yes
        groups:
          - docker

    - name: install python pip
      apt:
        name: python3-pip
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: install docker-py module
      pip:
        name: docker-py
        state: present

    - name: "Create directory"
      file:
        path: "/home/ubuntu/static-website"
        state: directory

    - name: "Git Clone"
      git:
        repo: "https://github.com/diranetafen/static-website-example.git"
        dest: "/home/ubuntu/static-website"
        force: yes

    - name: "Copy Index File From Template"
      template:
        src: /home/ubuntu/webapp2/templates/index.html.j2
        dest: /home/ubuntu/static-website/index.html
        
    - name: "Create httpd container"
      docker_container: 
        name: webapp
        image: httpd
        ports:
          - "8081:80"
        volumes:
          - "/home/ubuntu/static-website:/usr/local/apache2/htdocs/"
