- name: "attribute hostname on Master"
  hosts: ansible
  become: true
  vars_files:
  - secret.yaml
  vars:
    hostname: AnsibleMaster
  tasks:
    - name: set host name
      command: "sudo hostnamectl set-hostname {{ hostname }}"

    - name: edit the hosts file
      command: "echo '127.0.0.1 {{ hostname }}' >> /etc/hosts"


- name: "Install container apache with static-website"
  hosts: prod
  become: true
  vars_files:
  - secret.yaml

  pre_tasks:
    - name: set host name
      command: "sudo hostnamectl set-hostname {{ hostname }}"

    - name: edit the hosts file
      command: "echo '127.0.0.1 {{ hostname }}' >> /etc/hosts"

  tasks:
    - name: "Create directory"
      file:
        path: "/home/ubuntu/static-website"
        state: directory

    - name: "Git Clone"
      git:
        repo: "https://github.com/diranetafen/static-website-example.git"
        dest: "/home/ubuntu/static-website"
        force: yes

    - name: "Copy Index File From Template"
      template:
        src: templates/index.html.j2
        dest: /home/ubuntu/static-website/index.html

    - name: "Create httpd container"
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "8081:80"
        volumes:
          - "/home/ubuntu/static-website:/usr/local/apache2/htdocs/"
