---
- name: "Install container apache with static-website"
  hosts: prod
  become: true
  vars:
    ansible_sudo_pass: ubuntu

  tasks:
    - name: "Create directory"
      file:
        path: "/home/ubuntu/static-website"
        state: directory

    - name: "Git Clone"
      git:
        repo: "https://github.com/diranetafen/static-website-example.git"
        dest: "/home/ubuntu/static-website"
        force: yes

    - name: "Copy Index File From Template"
      template:
        src: /home/ubuntu/webapp2/templates/index.html.j2
        dest: /home/ubuntu/static-website/index.html

    - name: "Create httpd container"
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "8081:80"
        volumes:
          - "/home/ubuntu/static-website:/usr/local/apache2/htdocs/"
