all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      vars:
        env: production
        ansible_user: ubuntu
        ansible_password: ubuntu
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        worker01:
          ansible_host: 172.31.6.70
          hostname: AnsibleWorker01

        worker02:
          ansible_host: 172.31.13.73
          hostname: AnsibleWorker02
