- name: "Deploy a webapp nginx"
  hosts: prod
  vars_files:  secret.yaml

  tasks:
    - name: "Create directory"
      file:
        path: "/home/ubuntu/static-website"
        state: directory

    - name: "Git Clone"
      git:
        repo: "https://github.com/diranetafen/static-website-example.git"
        dest: "/home/ubuntu/static-website"
        force: yes

    - name: "Copy Index File From Template"
      template:
        src: templates/index.html.j2
        dest: /home/ubuntu/static-website/index.html

    - name: "Create httpd container"
      docker_container:
        name: nginx
        image: nginx
        ports:
          - "8080:80"
        volumes:
          - "/home/ubuntu/static-website:/usr/share/nginx/html/"
